

name: Maven Package

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
    - name: Build with Maven
      run: mvn clean install

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
