name: Build & Deploy

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - uses: a7ul/tar-action@v1.1.0
      with:
        command: c
        cwd: "./"
        files: |
          backend/
          frontend/dist/
          captain-definition
        outPath: deploy.tar

    - name: Deploy App to CapRover
      uses: caprover/deploy-from-github@v1.0.1
      with:
        server: http://192.168.10.200:3000/
        app: ap-pedidos
        token: '${{ secrets.API_PEDIDOS }}'
